# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "remastering_graphics" ]
  pull_request:
    branches: [ "remastering_graphics" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: [ubuntu-latest, macos-13, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile tt/build.xml dist
      
  build-windows:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile tt/build.xml build-windows
