# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "remastering_graphics" ]
  pull_request:
    branches: [ "remastering_graphics" ]
  workflow_dispatch:

jobs:      
  build-windows:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile tt/build.xml build-windows
    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: tt/build/dist/windows/
    
  build-mac-x86:
  
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build mac binaries
      run: ant -noinput -buildfile tt/build.xml build-mac-x86
    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: mac-x86
        path: tt/build/dist/macosx-x86/

  build-mac-arm64:
  
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build mac binaries
      run: ant -noinput -buildfile tt/build.xml build-mac-arm64
    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: mac-arm64
        path: tt/build/dist/macosx-arm64/
